#+title: Klava Values
Alright, let's take a look at the Klava first, shall we? The Klava is a transhylinxist coalition of planets. Essentially, they fund self-modification and such. But of course, I doubt that whoever is running the Klava is doing this purely out of the goodness of their hearts, so there must be some economical reason. Maybe the Klava is made up of corporations? Or private government labs? Or whatever?

Let's worldbuild that later. For now, we need to know that, to determine a culture's values, we need to see where they came from, what challenges they faced, and what they had to do to adapt.

- Where did the Klava come from?
  Let's say the Klava is a coalition of various private groups who want to make self-modification a reality (and already have, but are exploring it). A coalition of corporations, government subsidaries, genuinely benevolent non-profit organizations, religious groups, e.t.c.
- What challenges did the Klava face?
  - maybe prejudice from non-hylinxists?
  - potential abominations (and any abominations they actually did make)?  
  - potential subversion, either from the inside (via spies) or from the outside (via war or attacks)?  
- What did they have to do to adapt?
  - they might have had to try to make their ideology(s) look appealing, or at least acceptance. they might fund advertising campaigns.
  - they might also keep a private fleet to defend themselves
  - and they may regulate things HEAVILY to avoid subversion or creating abominations   
- what kind of culture(s) did they have before?
  - idk, gotta flesh this out LATER
  - gotta wonder if they have any values NOT related to transhylinxism? let's add some  
- what values therefore do they have?
  - zeal
  - military strength
  - vigilance  
  - transhylinxism (transhumanism for Hylinx)
  - piety
  - reservedness
  - openness
  - animism
  - obedience  
  - not making too much of a fuss  
  - pleasure
  
