#+title: Klava Potential Origins
- Alright, one idea I have for the Klava is that they are made up of MANY groups who want to achieve self-improvement through self-modification.
  - So why do they think so?
    - Well, why do some people NOWADAYS think that transhumanism is a good idea?
      - well, as someone who is somewhat sympathetic to transhumanism, I would say that augmenting yourself to be able to do things better is a pretty sweet deal, as long as the modifications don't have unintended consequences 
    - What kind of cultural factors make people see transhumanism as a good thing? and what make people see it as a bad thing?  
      - of course, Buddhism encourages you to "kill" your ego and ascend to Nirvana, so transhumanism could simply be seen as an extension.
  - such groups might include
    - businesses who see self-modification as good business
    - non-profit idealist groups  
      - charities
    - government subsidaries who want to be able to enhance people... for good or bad    
  - the conflict between the groups of this Coalition could be interesting to explore.
    - like for example, the groups might disagree about how to achieve self-improvement, what they should and shouldn't allow, and so on. or the non-profits might hate any greedy actions that any corporations take. or the government groups might be looking for quick power.
  - this is really the only plausible origin I can see, but let's discuss it with The Group.
