#+title: First Contact Mission Description
- Optionally, at first, you enter Hylinx territory. Then, one of the planets in the star system hails you and sends you a weird message. It clearly has pattern, and after hours of trying different data schemas on it, you find out that it is actually a set of chemicals: glucose, acetone, carbon buckyballs, and 30 others.
- Either directly or from the previous contact, you visit the Qulinx - Quarg who live in a few ringworlds nearby, around 5 - and ask a Quarg there for answers.
  - They tell you that you are in the sapce of the Hylinx, a group of plant and fungi species originating from Sawi, a steamy foggy world. It has recently gotten hotter, as its star enters the last few billion years of its life, and has only 3 billion to go...
  - You then ask them for help in contacting them.
    - Do they decline? That might make sense, if the Quarg wish to prevent interspecies conflict, but then again, you are only one explorer and likely won't go back to your people and gather a fleet of warships big enough to seriously threaten the Hylinx.
    - I think that they would give you a basic data chip that contains the most used Hylinx languages - their words, grammar, and subtle nuances, with translations in human languages.
- After that, you could go back to a Hylinx world and contact them directly, and they might send more hails to give you information about their culture and what they want to do with you. Not to you, or by you, but *with* you.
  - I believe that since they have mostly chemical senses and little visual sense - except for the Eyed Vines, who do have visual sense, albeit limited, in-person or physically close interactions are not important socially, so they don't care much for meeting in person, and barely even consider it.
- They might then offer some of their outfits and spaceships as a "trial run".
