#+title: Unique Traits For The Hylinx
- Thinking up unique traits for the Hylinx will be hard, but I'm determined to do so. And I think I should first start by thinking about how their very nature as Intelligent Plants will affect their outlook on the world
- As Intelligent plants, they may move slowly or not all, so they need to get their things some other ways. Regular plants can survive simply by passively gathering resources, but that does not need intelligence.
- Perhaps Intelligent Plants might need intelligence to cooperate, "command" their helper animals, come up with survival strategies, and such.
- Thus, they may not actually
- And what about plants who also serve as shelter for other species?
- Ooh! That one gives me an idea for a new species: the Canimalla, an oak-like tree species that houses ants and works with them to do stuff.
- Of course, chemical computing (maybe via modifiying or domesticating fungi) could be their precursor to more advanced "silicon-based computing", or they might not even use the latter at all! But of course, the latter is faster.
- Also, Hylinx species may have to cooperate with each other to survive, unlike humans, who are a single species, and thus they may be used to interspecies interactions. Of course, this doesn't mean that they are good at meeting new species; different species might have simply gotten use to each other. But this could drive the evolution of intelligence, if they need to account for the physiological and social differences of their "symbiote" species.
- Alright, I've thought up 8 ideas so far. But I need to come up with more. Of course, for them to evolve sapience, they would need to use tools. Lemme word that: to use tools, they would need to evolve sapience. And why would they need to use tools?
- Maybe they aren't the direct tool users, but instead get their helper animals to do such things for them? This may be where the Sporadic come in. let's say that the Sporadic aren't sapient, but definitely sentient, and roughly as intelligent as dolphins. That comparison might be meaningless, since dolphins and sporadic come from different *kingdoms* of life, but it will give readers an idea.
- Or maybe they use tools that we might not recognize at first, like fungi that they modify. Ooh! That's an idea!
- They might also simply be able to use tools themselves by moving slowly.
- I'm thinking that the ideal biome for them to evolve in is Tundras. I think that those places are kind of harsh? But I haven't heard of any plants in Tundras that have evolved intelligence. And I should also do my research on where most IRL "semi-intelligent" plant species live.
